name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Creating Mod file
      run: cd ../leadership && go mod init

    - name: Building Go repo
      run: go build -v ../leadership/main.go

    - name: Testing the build
      run: go run ../leadership/main.go
      
